### ISSUE TITLE
incompatible with Python 3.5

### ISSUE THREAD

**Issue by sashw** [serprex/byteplay#4]
The ``dis`` package has beed changed in Python 3.5: https://docs.python.org/3.5/library/dis.html
``WITH_CLEANUP`` is now split into ``WITH_CLEANUP_START`` and ``WITH_CLEANUP_FINISH``, hence byteplay can't be imported without a ``NameError`` in Python 3.5.

**Comment by abarnert** [comment]
`WITH_POP_BLOCK` is also gone in 3.5.

Anyway, I think the generic (`not in hasfllow`) code should work for `WITH_CLEANUP_START` and `WITH_CLEANUP_FINISH`? It seems right, but the fact that `WITH_CLEANUP` didn't use the generic code in 3.4 worries me.

Also, I wasn't sure how to do this cleanly. I took the two opcodes out of the `hasflow=` line, then added `if version_info.minor<=4: hasflow.add(WITH_CLEANUP,WITH_POP_BLOCK)` on the next line.

Meanwhile, there doesn't seem to be any test suite. But one of the other `byteplay` forks on GitHub has some code that walks a directory tree, inserting `__import__('sys').stderr.write('reassembled spam.pyc imported'` into the start of the bytecode for every .pyc file. So I copied that over, and ran it against a copy of the 3.5 stdlib tests. Some of the non-compiling tests and crashing tests failed, but everything else succeeded. And then I ran the unhacked and hacked copies of the test suite (disabling the non-compiling tests and the crashing tests, and also the muiltiprocessing tests because for some reason those sometimes spawn 4 new copies of the whole test suite on this Windows laptop), and got the same number of skips and failures.

I can submit a PR with the 3.5 fixes if desired. And if you want the test code as well, I can either submit that, or track down the fork I copied it from.

**Comment by serprex** [comment]
Sorry for my belated reply. This sounds good. I haven't used byteplay for awhile; last time I mucked in python bytecode I went with using dis raw: https://github.com/serprex/Befunge/blob/master/funge.py

So I've given you & peterazmanov commit rights to this repo

**Comment by peterazmanov** [comment]
@abarnert what code did you use for testing? The code from base version of [byteplay](http://byteplay.googlecode.com/svn/trunk/byteplay.py) works only with version of Python before 3.3 (pyc file format changed in that version). If you recompiled Python library with obsolete code all pyc files were overwritten with 'unhacked' versions by Python when you ran tests. Did you observe 'reassembled ...' messages while running tests? With these messages some tests had to fail as they compare stderr output with expected result.

In my fork I have updated version of test code with support of pyс new format (recompile_modules.py). You can try it to test your changes. [master version of byteplay](https://github.com/serprex/byteplay/blob/master/byteplay.py) will fail even without your changes. You can test version from my fork, when I tested it with Python 3.4.3 it failed with one additional test after recompile.

**Comment by peterazmanov** [comment]
In my [fork](https://github.com/peterazmanov/byteplay) I added support for Python 3.5 and tested it with recompile-Python-Lib. You can give it a try.

**Comment by serprex** [comment]
I've pulled pterazmanov's repo over mine
